### ISSUE TITLE
steam卡牌利润问题

### ISSUE THREAD

**Issue by yezheyu** [lzghzr/TampermonkeyJS#1]
steam卡牌利润最大化现在不能用了，不知道是不是我一个人的问题

**Comment by lzghzr** [comment]
@yezheyu 似乎并么有这样的问题，可以提供一下浏览器名称和版本么，最好有下载地址

**Comment by yezheyu** [comment]
好像是当时steam大姨妈了，现在又可以用了，对了dalao，问一下之前你在steamcn发的分享帖子地址在哪？我现在怎么找不到了？
----- 原始邮件 -----
发件人：lzghzr <notifications@github.com>
收件人：lzghzr/GreasemonkeyJS <GreasemonkeyJS@noreply.github.com>
抄送人：薛定谔的猫 <applyfor1230@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[lzghzr/GreasemonkeyJS]_steam卡牌利润问题_(#1)
日期：2017年03月04日 20点32分

@yezheyu 似乎并么有这样的问题，可以提供一下浏览器名称和版本么，最好有下载地址

&mdash;

**Comment by lzghzr** [comment]
@yezheyu https://steamcn.com/t199008-1-1
