### ISSUE TITLE
大佬您好

### ISSUE THREAD

**Issue by BlackAssassin** [lzghzr/TampermonkeyJS#12]
当时用了您抓包改包后的sony connect,但是没留副本,现在想抽空研究下,但是发现您帖子已经删除失效.可以麻烦您发一份吗?全机型的,自己研究学习用.期待并感谢您的回复~

**Comment by lzghzr** [comment]
恩，等我找找
________________________________

**Comment by lzghzr** [comment]
https://www.lanzous.com/b716165/
密?:sony
________________________________

**Comment by BlackAssassin** [comment]
多谢大佬
