### ISSUE TITLE
gb688的不能显示下载了

### ISSUE THREAD

**Issue by peqing** [lzghzr/TampermonkeyJS#13]
比如下面这个http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=79E67607CDA102BF3D9A6169849B40AC

**Comment by lzghzr** [comment]
最好能给我那个不显示的页面，预览页面没改版，我也不好确定是什么问题
________________________________

**Comment by peqing** [comment]
抱歉抱歉，我搞错了，请把这个删了，可以下载，实在抱歉
