### ISSUE TITLE
请问舰长上任可以屏蔽吗?

### ISSUE THREAD

**Issue by wialny** [lzghzr/TampermonkeyJS#14]
如图
![image](https://user-images.githubusercontent.com/12374028/64110046-9ee29400-cdb3-11e9-9a89-45ec1670fe32.png)
除了聊天和弹幕都钩了, 但这个还是会显示

**Comment by lzghzr** [comment]
抽奖没屏蔽，有需求的话可以加个开关
________________________________

**Comment by wialny** [comment]
感谢回复.
因为使用以下规则只能做到当次屏蔽, 第二天又会出现才来求助的, 希望能加上控制这个显示的开关. 
`live.bilibili.com###chat-draw-area-vm

live.bilibili.com###chat-draw-area-vm > .chat-draw-area-cntr

live.bilibili.com###chat-draw-area-vm > .chat-draw-area-cntr > .show.draw-full-cntr

live.bilibili.com##.draw-full-cntr.show`
谢谢
