### ISSUE TITLE
2019较新的国标下载的是错误文件

### ISSUE THREAD

**Issue by endest** [lzghzr/TampermonkeyJS#15]
例如GB/T 20256-2019
http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=6C3ADC832C06BA0EB68CD93BAC0DC371

下载得到的是GB/T 36919-2019，尝试直接搜索下载GB/T 36919-2019，得到的又是另一个国标。
但是预览看到的是正确的

这三个标准似乎都是19年较新的标准，下载旧标准没有这个问题

**Comment by lzghzr** [comment]
看了一眼, 是网站的问题, 使用iOS设备预览就会出错, 下载脚本模拟的iPad所以也跟着出错了
