### ISSUE TITLE
建议切换下载和获取地址到jsdelivr

### ISSUE THREAD

**Issue by Janet-Baker** [lzghzr/TampermonkeyJS#17]
github在国内的访问性能很差，尤其是raw部分甚至被墙了。
所以建议换成jsdelivr_（他们在国内有网宿科技的CDN）_，比如这样：
`// @require      https://cdn.jsdelivr.net/gh/lzghzr/TampermonkeyJS/libBilibiliToken/libBilibiliToken.user.js`
安装地址也可以换掉，比如`https://cdn.jsdelivr.net/gh/lzghzr/TampermonkeyJS/BiliveClientHeart/BiliveClientHeart.user.js`
jsdelivr的替换规则很简单，而且免费，全球连接性都很好。

推荐尝试。

**Comment by lzghzr** [comment]
jsdelivr是靠什么盈利的呢? 之前也用过一些支持国内镜像的服务, 但无一例外全部关闭了

**Comment by Janet-Baker** [comment]
jsdelivr `https://www.jsdelivr.com/`
由全球各地的组织捐赠和提供服务。

> jsDelivr is the only public CDN with a valid ICP license issued by the Chinese government, and hundreds of locations directly in Mainland China.

**Comment by lzghzr** [comment]
并没有在工信部查到jsdelivr.com备案号
看了一眼捐赠列表，最大的是cloudflare，而cloudflare在大陆的业务都是交给百度的
GitHub上即使有违反大陆法规的内容但依然能够访问是因为它的不可替代性，jsdelivr直接加速GitHub却没有过滤大陆违规内容，所以并不看好

**Comment by andywang425** [comment]
> 并没有在工信部查到jsdelivr.com备案号
> 看了一眼捐赠列表，最大的是cloudflare，而cloudflare在大陆的业务都是交给百度的
> GitHub上即使有违反大陆法规的内容但依然能够访问是因为它的不可替代性，jsdelivr直接加速GitHub却没有过滤大陆违规内容，所以并不看好

确实jsdelivr没有过滤违规内容。但我觉得只要开发者确保链接指向的内容符合规范就没问题。我写的一个油猴脚本库文件加起来有1MB，要是直接从github源加载实在太慢了。甚至有些用户连加载都加载不出来。
