### ISSUE TITLE
请问能让客户端心跳的脚本模拟手机播放吗？

### ISSUE THREAD

**Issue by Janet-Baker** [lzghzr/TampermonkeyJS#18]
B站更改了直播规则，在开播的、有那个房间的粉丝勋章的直播间，每观看5分钟可以获得一个小心心，每投喂一个小心心可以获得50亲密度。

在测试中发现，只有真的观看才可以获得。电脑上使用Flash播放器、或者只发送心跳的，都不能拿到。必须在开播主播直播间使用html5播放器播放才行。

所以、希望大佬能改一下脚本，能模拟真实播放就太好了。

**Comment by Janet-Baker** [comment]
想要小心心，还不想开html5的播放器……*_*

**Comment by lzghzr** [comment]
等客户端更新再说，网页版说改就改了

**Comment by lzghzr** [comment]
客户端加密(client_sign)使用了五重哈希, 看的实在头疼, 也不知道B站为了啥, 可能服务器太好闲的吧

**Comment by Janet-Baker** [comment]
emmm是为了防脚本的吧……毕竟我开脚本昨天刷了1万+的辣条=_ =
直播打赏的多了，自然有钱。。而且现在客户端更新迭代，也不怕客户端有多卡。
于是肆意妄为，逐渐毒瘤

**Comment by lzghzr** [comment]
试了一下难点在于多次hash对应的加密库, B站自己用的是webassembly, 脚本不知道能不能直接调用一下

**Comment by indefined** [comment]
前几天折腾了一通可以在直播间里调到签名方法，但是应该没办法直接调webassembly，46号webpack模块里也很多和加密相关的东西。可以调用46号模块里的东西去初始化webassembly，但是webpack入口被改过，而且B站这次前端更新得很频繁，在我折腾的过程它就至少更新了一次，现在能用它再更新一下就用不了了。而且感觉现在挂机也没什么意义，真看直播的话直接看就有了，不看的话那勋章亮不亮也没区别……所以我为什么要去瞎折腾这东西

顺便这神经病心跳竟然是有断点续传逻辑的，就算没到心跳时间它也时不时就签名一下然后存起来……

**Comment by lzghzr** [comment]
> 前几天折腾了一通可以在直播间里调到签名方法，但是应该没办法直接调webassembly，46号webpack模块里也很多和加密相关的东西。可以调用46号模块里的东西去初始化webassembly，但是webpack入口被改过，而且B站这次前端更新得很频繁，在我折腾的过程它就至少更新了一次，现在能用它再更新一下就用不了了。而且感觉现在挂机也没什么意义，真看直播的话直接看就有了，不看的话那勋章亮不亮也没区别……所以我为什么要去瞎折腾这东西
> 
> 顺便这神经病心跳竟然是有断点续传逻辑的，就算没到心跳时间它也时不时就签名一下然后存起来……

https://github.com/lkeme/bilibili-pcheartbeat 注意用的是GPL协议

有人成功调用了，看了一下是JS配合webassembly，JS主要负责填充内容(调用wasm完成)，wasm负责计算hash，填充内容这一块纯JS应该也能做，但是hash这不知道wasm里有没有做处理

当然不追求纯JS的话直接用上面的代码就行，但要注意GPL感染

**Comment by indefined** [comment]
> 
> https://github.com/lkeme/bilibili-pcheartbeat 注意用的是GPL协议
> 
> 有人成功调用了，看了一下是JS配合webassembly，JS主要负责填充内容(调用wasm完成)，wasm负责计算hash，填充内容这一块纯JS应该也能做，但是hash这不知道wasm里有没有做处理
> 
> 当然不追求纯JS的话直接用上面的代码就行，但要注意GPL感染

我自己调过了，那个JS填充数据的部分就是46号webpack里的东西，只是直播间网页端里用的话可以直接调用webpack里面的模块就行了，那个模块独立性挺高的，问题在不知道这个填充内容模块会不会更新，从我测试到现在它已经换过几次模块ID了，里面内容有没有变化我就不知道了，那团代码我读不下去。而且我只是瞎折腾一下暂时没打算把它做成完整工程

**Comment by lzghzr** [comment]
> 
> 我自己调过了，那个JS填充数据的部分就是46号webpack里的东西，只是直播间网页端里用的话可以直接调用webpack里面的模块就行了，那个模块独立性挺高的，问题在不知道这个填充内容模块会不会更新，从我测试到现在它已经换过几次模块ID了，里面内容有没有变化我就不知道了，那团代码我读不下去。而且我只是瞎折腾一下暂时没打算把它做成完整工程

那我试试把客户端那套拿到web上来吧(指打开《rust从入门到放弃》), 相对而言还简单一些, 但是app也支持热更新了, 虽然频率不高, 但也没有以前那种可以一个算法用几年的好日子了

**Comment by lzghzr** [comment]
https://github.com/lzghzr/TampermonkeyJS/commit/a16b12e9fac45f821ebf4c29acce68fa3d719979
