### ISSUE TITLE
国家标准不能下载了吗？

### ISSUE THREAD

**Issue by guohaiping** [lzghzr/TampermonkeyJS#20]
以前挺好用的，目前都不显示下载按钮了。是不是因为网站更新了，所以脚本失效了？

http://openstd.samr.gov.cn/

**Comment by lzghzr** [comment]
试了一下, 没什么问题

**Comment by guohaiping** [comment]
感谢作者，问题已解决。是我没有在油猴中启用脚本的缘故，低级错误！
