### ISSUE TITLE
【BiLiveNoVIP】直播回放页面不生效

### ISSUE THREAD

**Issue by Taohaotie** [lzghzr/TampermonkeyJS#21]
直播回放的页面  https://live.bilibili.com/record/*  脚本启动不起来，在油猴脚本设置里，添加了用户匹配 *://live.bilibili.com/record/* 
![SG_ E3I `HFPGXHZ8V7OUT](https://user-images.githubusercontent.com/33448919/99207705-a136df80-27f9-11eb-825a-d96bc1efb8fc.png)
刷新后页面能看见脚本有启动，但是回放页面会崩掉，提示找不到页面

**Comment by Taohaotie** [comment]
![GK`7PLZ@){}E3%%DRR7B260](https://user-images.githubusercontent.com/33448919/99207749-bb70bd80-27f9-11eb-9522-8b6c89ee0b40.png)

**Comment by Taohaotie** [comment]
我记得回放页面刚出来的时候是能正常生效的，现在是改版后哪里冲突了吗

**Comment by lzghzr** [comment]
大概是屏蔽房间皮肤这个功能冲突了，因为用到了重定向，关掉这个就行
本来没打算适配回放的，感觉用回放功能的人不多

**Comment by Taohaotie** [comment]
关掉屏蔽房间皮肤功能后页面能正常打开了。只是回放页面看不见脚本的按钮。。。但是能生效也可以了。
