### ISSUE TITLE
小心心好像失效了，大佬可以有空再搞一搞么~

### ISSUE THREAD

**Issue by FLYX-LL** [lzghzr/TampermonkeyJS#22]
小心心好像失效了，大佬可以有空再搞一搞么~

**Comment by lzghzr** [comment]
因为本来就是钻漏洞搞的，迟早会被修复的
我看看还能不能抢救一下

**Comment by lzghzr** [comment]
暂时修复了, 不过B站从原来5分钟一次心跳改成了1分钟一次, 所以不能瞬间挂24个了, 需要挂机5分钟

**Comment by FLYX-LL** [comment]
帅帅帅，感谢大佬！！
