### ISSUE TITLE
[bilibili直播净化] 直播间皮肤无法正常屏蔽

### ISSUE THREAD

**Issue by SettingDust** [lzghzr/TampermonkeyJS#23]
rt

**Comment by lzghzr** [comment]
你是指什么皮肤?

**Comment by SettingDust** [comment]
> 你是指什么皮肤?

![image](https://user-images.githubusercontent.com/19922286/102730343-67647600-436f-11eb-8906-3cd6f6437351.png)
目标：
![image](https://user-images.githubusercontent.com/19922286/102730352-70554780-436f-11eb-9042-75e8ace21a53.png)
![image](https://user-images.githubusercontent.com/19922286/102730369-7d723680-436f-11eb-8961-66f360a0c365.png)

后一张图是我用 Bilibili Evolved 达成的屏蔽效果 不过也不太完善 聊天栏还是带皮肤
![image](https://user-images.githubusercontent.com/19922286/102730408-a397d680-436f-11eb-81b3-e3b79e0c909a.png)

屏蔽其他脚本也测试过，确实无效

**Comment by lzghzr** [comment]
这个本来就没算在房间皮肤里
屏蔽皮肤指的是像6号房间那种，播放器内嵌在活动页的

要达到你想要的效果也行，只是我感觉没必要，代码里注释掉的就是你要的效果

**Comment by SettingDust** [comment]
> 这个本来就没算在房间皮肤里
> 屏蔽皮肤指的是像6号房间那种，播放器内嵌在活动页的
> 
> 要达到你想要的效果也行，只是我感觉没必要，代码里注释掉的就是你要的效果

我没找到代码里有注释部分 除了文件头

**Comment by lzghzr** [comment]
> 我没找到代码里有注释部分 除了文件头

我试了一下，这个金色的皮肤的应该是后加载的，即使是之前注释掉的那种方法也不行，想要屏蔽的话只能拦截请求了

**Comment by SettingDust** [comment]
https://s1.hdslb.com/bfs/static/blive/live-web-mng/static/js/app.60bda74ebaf60f8b5b68.js line 20168
https://api.live.bilibili.com/xlive/web-room/v1/index/getInfoByRoom?room_id=5050 data.skin_info 是第一个XHR请求一起拿到的 不是后加载的 可能是后渲染
