### ISSUE TITLE
gb688现在下载标准好像不行了，请老大检查更新

### ISSUE THREAD

**Issue by itspidercn** [lzghzr/TampermonkeyJS#26]
下载进度开始后，就弹窗显示下载错误
![image](https://user-images.githubusercontent.com/62824108/105729000-b8b3e680-5f67-11eb-9f51-2389d204c8fd.png)
HTTP错误404：您正在搜索的页面可能已经删除、更名或暂时不可用

下载进度显示到100%，弹窗的内容依然不变，
没法下载了，真伤心

**Comment by lzghzr** [comment]
给个地址，我试了几个都没问题

**Comment by lzghzr** [comment]
#27
