### ISSUE TITLE
GB 688失效了

### ISSUE THREAD

**Issue by fancyfine** [lzghzr/TampermonkeyJS#28]
不好意思，不是程序员，不太懂这个github的逻辑，我看更新说gb688提供下载了，好像还没有提供，推荐性标准没有，然后下载下载的失效了，不知还更新不。
感谢你的无私劳动。

**Comment by lzghzr** [comment]
具体的讨论在 #27 主要是因为法律风险不再提供下载工具，但下载的思路在 [这里](https://gist.github.com/lzghzr/858067598cf590af4c1b7d8faa211d21) 可以自己制作或者找人代写(本人不接代写)

**Comment by fancyfine** [comment]
谢谢
