### ISSUE TITLE
【gb688】gb688改版之后，还是有大量无法直接下载的标准，原来的接口又失效了（抓狂）

### ISSUE THREAD

**Issue by renmu123** [lzghzr/TampermonkeyJS#30]
gb688中还是存在大量只能在线预览而无法下载的标准
如：
1. http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=3A8122A4888682C1103233241B646A3C
2.  http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=E675EA7C043BA828DCBA1F2C2567076E

我之后去抓了最新api的包，虽然说也是分段加载但好像并不是用base64来进行编码，
我开始以为是开发者用了什么加密方式，用f12 debug了好久也没找到加密方法，已经折腾好几天了（头发越来越少了）

已知信息：
1.  采用pdf.js来进行渲染
2. 采用 stream 来进行分段加载
3. 并非采用 base64 编码

**Comment by lzghzr** [comment]
#27
