### ISSUE TITLE
[BiLiveNoVIP] 大航海名单无法读取

### ISSUE THREAD

**Issue by Mishasama** [lzghzr/TampermonkeyJS#32]
激活【屏蔽视频轮播】或者【[隐身入场](https://github.com/lzghzr/TampermonkeyJS/issues/31)】后，会导致无法显示大航海名单。
这个名单无需登陆也能看到的，应该跟用户状态无关的吧？会不会是误杀？

**Comment by lzghzr** [comment]
把去广告插件关了试试，比如ublock

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Misha "<notifications@github.com&gt;;
发送时间：2021年3月1日(星期一) 晚上10:05
收件人："lzghzr/TampermonkeyJS" <TampermonkeyJS@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[lzghzr/TampermonkeyJS] [BiLiveNoVIP] 大航海名单无法读取 (#32)
-----------------------------------

 

 
激活【屏蔽视频轮播】或者【隐身入场】后，会导致无法显示大航海名单。
 这个名单无需登陆也能看到的，应该跟用户状态无关的吧？会不会是误杀？

**Comment by Mishasama** [comment]
> 把去广告插件关了试试，比如ublock

![image](https://user-images.githubusercontent.com/54498172/109685876-0950dc00-7bc5-11eb-8336-279b9fc31dee.png)

咦？为什么会这样？
不用脚本的时候就不会被去广告而导致消失掉……好奇怪

**Comment by lzghzr** [comment]
具体原因还没去了解，但实际上不用脚本大航海也被ublock拦截了
至于为啥用脚本就直接没数据，大概是因为脚本把房间预置数据清除了
