### ISSUE TITLE
windows10下载EXE以后提示危险？

### ISSUE THREAD

**Issue by mardak-cn** [lzghzr/TampermonkeyJS#33]
windows10下载EXE以后提示危险？
![image](https://user-images.githubusercontent.com/81667136/113090169-beee6980-921b-11eb-8c91-880caed4275f.png)
怎么办呢

**Comment by lzghzr** [comment]
哪来的exe？

**Comment by mardak-cn** [comment]
https://github.com/renmu123/gb688_downloader/releases/tag/2.1
***@***.***D72630.66C0B530]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年3月31日 12:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [lzghzr/TampermonkeyJS] windows10下载EXE以后提示危险？ (#33)


哪来的exe？

―

**Comment by mardak-cn** [comment]
> 特蕾斯·比特克斯？
这里
https://github.com/renmu123/gb688_downloader/releases/tag/2.1
![image](https://user-images.githubusercontent.com/81667136/113094160-cade2980-9223-11eb-8b18-90f1ac17df88.png)

**Comment by lzghzr** [comment]
你找错地方了 去  https://github.com/renmu123/gb688_downloader/issues
