### ISSUE TITLE
[BiLiveNoVIP] 活动页屏蔽范围意见征集

### ISSUE THREAD

**Issue by lzghzr** [lzghzr/TampermonkeyJS#35]
比如 [https://live.bilibili.com/blackboard/activity-V4ve9Ip9F.html](https://live.bilibili.com/blackboard/activity-V4ve9Ip9F.html) 这种一个活动页面多个直播间切换的活动房间需不需要屏蔽

**Comment by Mishasama** [comment]
建议做一个分支选项给那些觉得这很烦人的用户单独启用。
毕竟有活动互动内容（比如永远不可能中奖的抽奖），并不是单纯的一个BANNER模板，我觉得一刀切不太妥。

P.S. 下次有调研建议更新一下脚本做个一次性的页面POPUP，不然真的没几个人知道你发了个issue……

**Comment by lzghzr** [comment]
> 建议做一个分支选项给那些觉得这很烦人的用户单独启用。
> 毕竟有活动互动内容（比如永远不可能中奖的抽奖），并不是单纯的一个BANNER模板，我觉得一刀切不太妥。
> 
> P.S. 下次有调研建议更新一下脚本做个一次性的页面POPUP，不然真的没几个人知道你发了个issue……

因为我不喜欢脚本没事弹个窗，所以就没做
