### ISSUE TITLE
[BiLiveNoVIP] 屏蔽挂机检测疑似失效

### ISSUE THREAD

**Issue by Sewiahho** [lzghzr/TampermonkeyJS#37]
长时间离开标签页后台或长时间无操作仍会触发B站的挂机检测，会弹出提示弹窗（弹窗一闪而过未成功截图内容为：检测到已离开屏幕 0）。
环境：Firefox 91.0.1 64
Tampermonkey 4.13.6136

**Comment by lzghzr** [comment]
我自己测试的都是开播前挂机，下播继续挂机，再次开播会失效
猜测是直播页面重新加载了player，导致player暂时处于前台，但其他脚本仍处于后台模式，处于后台模式的脚本`setInterval`循环周期会加长，无法覆盖player的循环检测
感觉常规手段应该是没法修复这个问题，不知道代码注入到player里会不会好一些

**Comment by andywang425** [comment]
或许可以试试劫持setTimeout和setInterval，比如这样
```js
  const W = typeof unsafeWindow === 'undefined' ? window : unsafeWindow;
  let _setTimeout = window.setTimeout;
  let _setInterval = window.setInterval;
  W.setTimeout = function (func, ...args) {
      if (String(func).indexOf('triggerSleepCallback') !== -1) return null
      else return _setTimeout.call(this, func, ...args)
  }
  W.setInterval = function (func, ...args) {
      if (String(func).indexOf('triggerSleepCallback') !== -1) return null
      else return _setInterval.call(this, func, ...args)
  }
```
`triggerSleepCallback`可以在这个b站的js里找到 https://s1.hdslb.com/bfs/static/blive/blfe-live-room/static/js/457.d815e482eeff21d5ec05.js

**Comment by lzghzr** [comment]
> 或许可以试试劫持setTimeout和setInterval，比如这样
> 
> ```js
>   const W = typeof unsafeWindow === 'undefined' ? window : unsafeWindow;
>   let _setTimeout = window.setTimeout;
>   let _setInterval = window.setInterval;
>   W.setTimeout = function (func, ...args) {
>       if (String(func).indexOf('triggerSleepCallback') !== -1) return null
>       else return _setTimeout.call(this, func, ...args)
>   }
>   W.setInterval = function (func, ...args) {
>       if (String(func).indexOf('triggerSleepCallback') !== -1) return null
>       else return _setInterval.call(this, func, ...args)
>   }
> ```
> 
> `triggerSleepCallback`可以在这个b站的js里找到 https://s1.hdslb.com/bfs/static/blive/blfe-live-room/static/js/457.d815e482eeff21d5ec05.js

好主意

**Comment by Sewiahho** [comment]
相同问题再次出现。
