### ISSUE TITLE
[BiLiveNoVIP] 屏蔽挂机检测失效

### ISSUE THREAD

**Issue by Sewiahho** [lzghzr/TampermonkeyJS#39]
[长时间离开标签页后台或长时间无操作仍会触发B站的挂机检测，会弹出提示弹窗（截图内容为：检测到已离开屏幕] 0）。 环境：Firefox 93.0 64 Tampermonkey 4.13.6136
![4](https://user-images.githubusercontent.com/53895408/136517509-2b97dffd-1757-41bf-826e-651cb80451e1.jpg)

**Comment by lzghzr** [comment]
有可能是灰度测试？我这还没有这种情况
