### ISSUE TITLE
BiliveHeart的问题

### ISSUE THREAD

**Issue by Ranlajetech** [lzghzr/TampermonkeyJS#40]
B站获取包裹列表的API当包裹是空时，返回数据是null，导致data.list.length存在错误
![biliveheart](https://user-images.githubusercontent.com/56589757/142026273-a8a65641-9406-4c58-9264-6a52ae588f78.png)
错误在上图标绿的第200行触发
![biliveheart_api](https://user-images.githubusercontent.com/56589757/142027153-f471f3a3-5a39-4d99-a782-3a5fae4f50c0.png)
这是api的返回数据

**Comment by lzghzr** [comment]
当时没考虑过这个问题，有时间修一下
