### ISSUE TITLE
BiliveHeart粉丝勋章列表获取出错

### ISSUE THREAD

**Issue by Ranlajetech** [lzghzr/TampermonkeyJS#42]
js脚本Line233，`api.live.bilibili.com/i/api/medal?page=1&pageSize=10` 这个api好像是被B站改了，现在无法正确返回勋章列表，始终显示“用户不存在”，我没有其他账号验证是我账号的问题还是api的问题。现状是返回`{"code":510001,"msg":"用户不存在","message":"用户不存在","data":[]}`，造成Line251处`fansMedalList.length`报错，`TypeError: Cannot read properties of undefined (reading 'length')`

一个可替代的api是`api.live.bilibili.com/xlive/app-ucenter/v1/user/GetMyMedals?page_size=10&page=1`，这个response结构可能和原api不太一致，后续代码需要稍作修改，但至少可以满足获取勋章列表功能。

**Comment by lzghzr** [comment]
用Web端API就是这点麻烦，说不定哪天就改了
