### ISSUE TITLE
bilibili直播净化 开启部分功能导致直播间无法正常加载

### ISSUE THREAD

**Issue by Franinc** [lzghzr/TampermonkeyJS#44]
屏蔽房间皮肤，屏蔽视频轮播，屏蔽挂机检测，隐身入场 开启任意一项功能后刷新网页，直播间无法正常加载 只显示零星几张直播间原有的图。

测试用的地址 https://live.bilibili.com/blanc/92613

另外留言栏显示别人的醒目留言是否正常？前几天出现过几次主播念完sc我这留言栏空空如也，我再观察观察

**Comment by lzghzr** [comment]
应该是B站更新了，导致脚本冲突

**Comment by lzghzr** [comment]
也不太对，我完全关了脚本也打不开直播间，不知道是不是B站崩了

哦，是Ajax-hook导致的，我看看能不能去掉这个依赖

**Comment by Franinc** [comment]
感谢修复，才找到醒目留言失踪是测试时关脚本后全开了b站自带屏蔽，于是开启脚本后变成：b站设置屏蔽sc 但脚本不屏蔽sc，且只能看见脚本的选项😂
小事情就不开新issue了
