### ISSUE TITLE
[BiLiveNoVIP] 屏蔽选项“…”排版问题

### ISSUE THREAD

**Issue by Mishasama** [lzghzr/TampermonkeyJS#45]
![image](https://user-images.githubusercontent.com/54498172/163540002-fe7ce78d-d7bf-4c52-8dbf-6bac39e9e446.png)
是不是列宽少了几个像素？改成自适应如何？

**Comment by lzghzr** [comment]
你是指省略号吗

**Comment by Mishasama** [comment]
> 你是指省略号吗

嗯

**Comment by lzghzr** [comment]
目前来说确实不够友好，鼠标放在文字上也没做滚动效果，但自适应宽度就没法对齐了，实在是太丑，我是没法接受的

**Comment by Mishasama** [comment]
> 目前来说确实不够友好，鼠标放在文字上也没做滚动效果，但自适应宽度就没法对齐了，实在是太丑，我是没法接受的

???
你是各选项独立一单元格的？！
外面再套个自适应列宽的两列来统一第二列的起点不就对齐了吗？

**Comment by lzghzr** [comment]
> ??? 你是各选项独立一单元格的？！ 外面再套个自适应列宽的两列来统一第二列的起点不就对齐了吗？

这个自适应宽度是B站自带的，不统一宽度就会是这种效果
![2022-05-07_18-41-21](https://user-images.githubusercontent.com/13391314/167250909-2930a733-0591-4e19-9587-8e9587eb48b0.png)

**Comment by Mishasama** [comment]
那能不能覆盖掉它的样式？
![image](https://user-images.githubusercontent.com/54498172/167510263-5d76f6dc-c44b-48be-81e7-cf461b7831ba.png)
这里再挪一下应该是够用的？

**Comment by lzghzr** [comment]
把所有选项全部重命名了，现在应该没有`...`的问题了

**Comment by Mishasama** [comment]
嗯，没有问题了。
