### ISSUE TITLE
小心心改版了，亲密度获取方式改了，大佬有计划更新么？

### ISSUE THREAD

**Issue by FLYX-LL** [lzghzr/TampermonkeyJS#49]
https://link.bilibili.com/p/eden/news#/newsdetail?id=2780

**Comment by lzghzr** [comment]
没看懂公告说的啥……

**Comment by FLYX-LL** [comment]
> 没看懂公告说的啥……

获得小心心=获得亲密度的意思，然后以后小心心只在小心心活动才会显示数量或消耗，平时看不到，获得了表现形式就是亲密度增加。

**Comment by FLYX-LL** [comment]
> 没看懂公告说的啥……

相当于获得即送出，亲密度增加，各个粉丝牌独立计算

**Comment by FLYX-LL** [comment]
有人写了python版供参考：https://github.com/XiaoMiku01/fansMedalHelper
供参考：https://www.bilibili.com/read/cv16769141
大概看了一下，和之前发送心跳获取小心心是类似的，应该是懂者不难，就写起来比较简单吧大概

**Comment by lzghzr** [comment]
看了一下，我并不想写网页端自动获取经验的东西，因为这个很多人做了
之前写小心心自动获取也是为了解决加密问题，让其他人可以更方便的集成小心心功能
新版道具获取没有加密，只是单纯的请求api而已，这个我之前提供过工具 [libBilibiliToken](https://github.com/lzghzr/TampermonkeyJS/tree/master/libBilibiliToken)
可以等 [BLTH](https://github.com/andywang425/BLTH) 的作者更新

**Comment by FLYX-LL** [comment]
> 

我自己研究了一下，已经写好了，可以用，谢大佬的工具。

**Comment by andywang425** [comment]
> 可以等 [BLTH](https://github.com/andywang425/BLTH) 的作者更新

感谢大佬提供的库，我已经在写了。

**Comment by lzghzr** [comment]
> 感谢大佬提供的库，我已经在写了。

现在主播未直播的话，直接发送心跳包还可以获取亲密度吗

**Comment by andywang425** [comment]
> > 感谢大佬提供的库，我已经在写了。
> 
> 现在主播未直播的话，直接发送心跳包还可以获取亲密度吗

还是可以的。
