### ISSUE TITLE
进入直播间，没有界面，不好使了

### ISSUE THREAD

**Issue by TyKiri** [lzghzr/TampermonkeyJS#50]
![image](https://user-images.githubusercontent.com/113178420/208305075-e92a80e9-d549-426b-b48c-0f8636ce2127.png)
[](url)

**Comment by lzghzr** [comment]
信息太少了，最起码给个浏览器，脚本和Tampermonkey的版本啊

**Comment by TyKiri** [comment]
edge 脚本是bilibili直播净化 版本4.0.20
