### ISSUE TITLE
屏蔽挂机检测和隐身入场失效了 一直看会加贡献值 不知道是B站机制改了还是脚本失效了

### ISSUE THREAD

**Issue by AyNtea** [lzghzr/TampermonkeyJS#51]
360极速浏览器， 4.0.20

**Comment by lzghzr** [comment]
啥贡献值？

**Comment by AyNtea** [comment]
新加的东西 只要在看直播就会显示在哪里 隐身看也会加

**Comment by AyNtea** [comment]
![image](https://user-images.githubusercontent.com/106818791/210796458-0866614d-8009-4f1e-ac85-d95a3d3b874d.png)

**Comment by lzghzr** [comment]
试了一下，没发现这个东西
但从原理上讲，确实没有屏蔽观看直播加经验的功能
