### ISSUE TITLE
bilibili直播净化 弹幕礼物屏蔽好像失效了（小时榜抽红包之类的公告弹幕）

### ISSUE THREAD

**Issue by Franinc** [lzghzr/TampermonkeyJS#52]
网页全屏，最近出现的，连带着网页全屏底部的菜单的画质按钮边上也多出来个送礼物按钮。
留言列表看不见这些礼物，好像只是网页全屏才有礼物弹幕？没测试

如下图，弹幕礼物好像在`class="web-player-inject-wrap"`里的`id="gift-control-vm" class="full-screen-gift-panel-section"`这条
这一条看起来只会在有礼物时才出现，刚打开直播间没有这条，礼物弹幕结束一段时间后消失？

![%(_QU031H73{VT~ 4Q6Y0{E](https://user-images.githubusercontent.com/26399054/211153501-c54fa71d-dd69-4ce7-8251-4dd83a26958a.png)

`<div id="gift-control-vm" class="full-screen-gift-panel-section" style="position: absolute; right: -15px; bottom: -37px; display: inline-block !important;">`

**Comment by lzghzr** [comment]
我观察一下，平时也没有全屏看过

**Comment by Franinc** [comment]
~~这两天又没了，可能阿b最近在调试吧，也可能是先改了弹幕然后才跟进原版屏蔽~~

换了个直播间又出现了，我把原版的礼物屏蔽打开试试先
