### ISSUE TITLE
b站直播聊天区新加了两个弹窗

### ISSUE THREAD

**Issue by Franinc** [lzghzr/TampermonkeyJS#54]
如下图，“舰长进入直播间” 和 “主播帮玩游戏” 弹窗

不过我还停在chrome 102，可能老哥已经加了屏蔽但我这没生效？

```
<div id="welcome-area-bottom-vm" class="welcome-section-bottom"><!----></div>

<div data-v-27f6fac0="" data-v-3b153d34="" class="play-together-service-card-container"><iframe data-v-27f6fac0="" src="https://live.bilibili.com/live-room-play-game-together?ruid=114514#/serviceCard" onload="function () { [native code] }" class="card-iframe"></iframe><div data-v-27f6fac0="" class="close"></div></div>
```

![Snipaste_2023-11-20_19-03-31](https://github.com/lzghzr/TampermonkeyJS/assets/26399054/3b2a0fcd-ed94-4315-9dd2-c59ba5a3c949)
![Snipaste_2023-11-20_19-07-32](https://github.com/lzghzr/TampermonkeyJS/assets/26399054/bee2ad05-521d-4839-a98a-7b1ecf926c90)

**Comment by lzghzr** [comment]
是，舰长屏蔽需要chrome105以上，因为舰长和荣誉勋章分开了
“帮你玩”倒是不需要，也加了屏蔽，我看看是不是B站又改了什么东西

**Comment by lzghzr** [comment]
看了下我这没问题，在“屏蔽互动游戏“里

**Comment by Franinc** [comment]
那没事了 多谢老哥 舰长我换ublock屏蔽

**Comment by lzghzr** [comment]
倒是可以加一个兼容进去，有些好奇为什么不升级chrome呢

**Comment by lzghzr** [comment]
> 倒是可以加一个兼容进去

兼容版本降低到chrome 88

**Comment by Franinc** [comment]
不了不了 感谢老哥 不升级的人占比太少 就不浪费老哥时间了。
没升级单纯是我懒，cent到猫眼迁移太麻烦，而且还有优先级更高的问题比如win10太久没重装 新outlook应用无法登陆bug无法解决（微软社区最后建议用回旧版 但旧版年底说不定强制跳转新版？乐），于是浏览器这块就一拖再拖
