### ISSUE TITLE
[BiLiveNoVIP] 屏蔽轮播失效？

### ISSUE THREAD

**Issue by Mishasama** [lzghzr/TampermonkeyJS#56]
破站更新了？
另一个叫追帧的脚本所用的屏蔽方法倒是没有失效……

**Comment by lzghzr** [comment]
进直播间时效还是主播下播时效了？

**Comment by Mishasama** [comment]
进房，自己开不了播没测试过下播。

**Comment by lzghzr** [comment]
可能我还没收到更新？昨晚试了一下进房和下播都正常工作

**Comment by Mishasama** [comment]
能不能加个控制台输出看看问题在哪里？我看最近出问题的脚本挺多的，不知道是不是MV3还是ADB之类导致的问题。
不用推送更新，就把代码贴这我本地看一下就好。

可以的话最好像这样加个标签，不然条目太多了分不清是谁报的错……
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/802ed848-19d2-48fd-94c1-49ae7666897a)

**Comment by lzghzr** [comment]
其实是有输出的，但没有做标签，确实比较隐身

**Comment by Mishasama** [comment]
我看了一下，我这边这个脚本好像并没有输出什么到控制台。就是说执行了却没有效果？

**Comment by Mishasama** [comment]
最新更新后 Edge 126 在 TM 5.1.1 下测试通过，但 Chrome 126 的 TM 5.2.0 下依旧失效。
怀疑是 MV3 的锅？我好像依旧没看出有什么控制台输出……

**Comment by lzghzr** [comment]
> 最新更新后 Edge 126 在 TM 5.1.1 下测试通过，但 Chrome 126 的 TM 5.2.0 下依旧失效。 怀疑是 MV3 的锅？我好像依旧没看出有什么控制台输出……

这有可能，我用的也是edge，我下个chrome试试

**Comment by lzghzr** [comment]
> 最新更新后 Edge 126 在 TM 5.1.1 下测试通过，但 Chrome 126 的 TM 5.2.0 下依旧失效。 怀疑是 MV3 的锅？我好像依旧没看出有什么控制台输出……

试了下 `126.0.6478.127` 没问题

**Comment by Mishasama** [comment]
我很疑惑……
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/cc45be6b-ef1b-4d09-aba5-da7dcd316178)

也许这是唯一的线索……
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/d55a0158-fdbc-4870-9505-54eabb9f5658)
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/aa5da06f-07c5-41a3-abeb-2cfb038cd963)
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/b6469ef1-9b18-407f-9168-a25426b76ba7)
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/f86bf681-cef0-4bf9-a715-4a706998e315)

**Comment by Mishasama** [comment]
一个有趣的现象：
当另一个脚本[BLTH](https://github.com/andywang425/BLTH)的这个元素成功显示的时候，轮播拦截失败
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/960b0e1b-61b6-4c55-ac34-180023f7bb6e)
当这个元素无法显示的时候，轮播拦截成功……

反复测试后发现两个脚本有功能上的冲突……


更有趣的是：
当单独使用净化时，轮播无法屏蔽。
当净化与[BLTH](https://github.com/andywang425/BLTH)组合使用时，[BLTH](https://github.com/andywang425/BLTH)的按钮必然会无法出现。同时轮播无法被屏蔽。
当净化与[Bilibili直播自动追帧](https://greasyfork.org/zh-CN/scripts/453967)组合时，净化无法屏蔽轮播。
当净化与[BLTH](https://github.com/andywang425/BLTH)加上[Bilibili直播自动追帧](https://greasyfork.org/zh-CN/scripts/453967)同时使用时，净化有概率成功屏蔽轮播……
（概率约为29%：17次刷新中有5次成功屏蔽）


测试环境：
Chrome 126.0.6478.127

可能参与干涉的扩展：
ACG助手
Privacy Badger
uBlock Origin

**Comment by lzghzr** [comment]
我这三个脚本也都在用，挺正常的
BiLiveNoVIP 屏蔽轮播是用的 inlinehook，在js脚本初始化函数后，加载函数前对其进行修改，理论上兼容性非常好，不会与任何hook XMLHttpRequest，fetch或者WebSocket的脚本冲突
但也因为脚本需要在函数加载前介入，所以必须尽早加载脚本，一旦错过函数的加载，那么hook就会失败，导致功能失效

**Comment by lzghzr** [comment]
我不太清楚Tampermonkey的加载顺序，不过你可以把BiLiveNoVIP放在第一位试试

**Comment by Mishasama** [comment]
> 把BiLiveNoVIP放在第一位试试

没区别，要不你试试模拟龟速网络？比如完整载入直播间起码要30秒这样的。甚至模拟一下丢包？

载入开始
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/56350314-aeee-4633-9077-d9f40b2424fb)
到开始加载轮播视频
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/2a555713-d764-42b8-aada-88a36b6a8121)
注意看时间戳

**Comment by lzghzr** [comment]
我发现 `屏蔽活动皮肤` 和 `屏蔽视频轮播` 在一起才会生效

**Comment by Mishasama** [comment]
> 我发现 `屏蔽活动皮肤` 和 `屏蔽视频轮播` 在一起才会生效

但是我基本上就没开过屏蔽皮肤……测试偶然成功屏蔽轮播的时候也是没开的。感觉好奇怪……

话说以前都没有这些问题的，怎么最近这些灵异事件开始集中爆发了？
我想不是B站暗改就是chrome核心升级的问题，真是磨人😑

**Comment by lzghzr** [comment]
更新后应该可以了

**Comment by Mishasama** [comment]
> 更新后应该可以了

![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/0af02e1d-1f90-42ed-b288-924821dce5bd)
.38实测通过，chrome上也没问题了，控制台能正常输出了。

👍×1000

**Comment by lzghzr** [comment]
因为又把xhr hook加回来了，这样能解决问题，但兼容性也会差一些，我看了一下和追帧有冲突，不过不影响使用

chrome偶尔用不了应该是和脚本缓存有关系，我对比了一下，chrome打开直播间要快得多，这也导致了即使hook函数生效了，但由于chrome的提前响应，修改过的函数实际也不会起作用

**Comment by Mishasama** [comment]
> 脚本缓存

那我们有没有办法去解决这个问题？或者用户自己手动解决？
