### ISSUE TITLE
改用xhook后轮播一直在转圈

### ISSUE THREAD

**Issue by Mishasama** [lzghzr/TampermonkeyJS#57]
![image](https://github.com/lzghzr/TampermonkeyJS/assets/54498172/dac17134-fc60-47ce-bd0c-0bd6c6b5c42f)

https://github.com/lzghzr/TampermonkeyJS/commit/378168c393262d8a070666d18ae57a8c6853665c
这xhook稳定性不行，刷新几次大约只有1%能正常显示展示墙，无论缓存状态如何。
回退.38后发现功能正常，在有缓存的情况下稳定发挥，但刷新缓存初始化时会失效。
---
### 测试环境
edge
3G龟速网络

**Comment by lzghzr** [comment]
我这没办法复现，换xhook也是为了方便，b站加载房间信息有时候用的fetch有时候是xmlhttprequest
加载转圈圈说明已经hook成功了，因为我怕出问题，直接把视频地址重定向到404了，所以加载不出来

**Comment by Mishasama** [comment]
https://github.com/andywang425/BLTH/issues/502#issuecomment-2206533365
目前这个脚本似乎会拖慢载入导致BLTH的VUE更加容易出现载入超时的现象……关闭脚本后就缓解了。


> 我这没办法复现

尝试模拟低速网络，可以通过F12模拟或者其他防火墙控制一下流量在64KB/s以下看看。


话说为什么xhook会有问题而ajaxhook却不会有问题呢？
这两个能不能组合在一起用来覆盖所有的情况？

**Comment by lzghzr** [comment]
> 这两个能不能组合在一起用来覆盖所有的情况？

可以，再早些就是这么做的，但是ajaxhook挺长时间没更新了，不知道有没有啥bug

**Comment by Mishasama** [comment]
> 不知道有没有啥bug

长时间没更新不就证明它完美无瑕无bug可修么😏
