### ISSUE TITLE
bilibili直播净化导致进不去直播间

### ISSUE THREAD

**Issue by Franinc** [lzghzr/TampermonkeyJS#58]
看来阿b更新了，开启脚本后直播间无法加载，播放器全黑 周围全白

**Comment by lzghzr** [comment]
你都开了什么功能？我试了一下挺正常的
![image](https://github.com/user-attachments/assets/8a9ba2b6-87ef-4995-8a24-1f83b3207ed5)

**Comment by Franinc** [comment]
只要开脚本就不行，篡改猴恢复出厂也不好使。
换了只有一个扩展+一个脚本的edge也同样问题。
篡改猴5.1.1：https://chrome.google.com/webstore/detail/lcmhijbkigalmkeommnijlpobloojgfn
脚本版本4.2.43

**Comment by Taohaotie** [comment]
我的篡改猴5.2.3
脚本4.2.43打开直播间也是同上，直播间无法加载，播放器全黑 周围全白

**Comment by lzghzr** [comment]
给个直播间号？

**Comment by Franinc** [comment]
https://live.bilibili.com/25034104
首页推荐的十个都不行
edge清了所有数据，单扩展+单脚本，不登录直接开直播间也这样

**Comment by lzghzr** [comment]
> https://live.bilibili.com/25034104 首页推荐的十个都不行 edge清了所有数据，单扩展+单脚本，不登录直接开直播间也这样

奇了怪了，又是灰度更新？

**Comment by Taohaotie** [comment]
突然不開代理可以正常進了，開了代理還是存在問題。可能是有什麽測試

**Comment by xxxxuanran** [comment]
![image](https://github.com/user-attachments/assets/87c56b55-3421-43b0-96c8-b6db7f4791e9)
我也遇到了相同的问题，在清空脚本数据后可以加载直播流，但是登陆和礼物如上图所示。
尝试打开 Devtools 在网络面板监控，并点击图上蓝字，发现并无请求发出。
目前降级到 [2175fb](https://github.com/lzghzr/TampermonkeyJS/commit/2175fb9d326653b6b5224f900c8c2e01af5c98ad) 后正常
运行环境 Chrome `127.0.6533.73` + Tampermonkey `5.1.1`，直播间为 https://live.bilibili.com/732

**Comment by lzghzr** [comment]
> ![image](https://private-user-images.githubusercontent.com/31968665/353480265-87c56b55-3421-43b0-96c8-b6db7f4791e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTMwODYsIm5iZiI6MTcyMjM5Mjc4NiwicGF0aCI6Ii8zMTk2ODY2NS8zNTM0ODAyNjUtODdjNTZiNTUtMzQyMS00M2IwLTk2YzgtYjZkYjdmNDc5MWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAyMjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYTIxNGFlMThlZGEzZDU5YWY2OTBhMTYzOTVlNjBkYzBiOTYyODlhZTRjYzljNjA3NWVlYzdlNjA0YTliOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sxiUuDSd2NbohDNaADxv4PR5JXD5TxJrNPirCy_Hn04) 我也遇到了相同的问题，在清空脚本数据后可以加载直播流，但是登陆和礼物如上图所示。 尝试打开 Devtools 在网络面板监控，并点击图上蓝字，发现并无请求发出。 目前降级到 [2175fb](https://github.com/lzghzr/TampermonkeyJS/commit/2175fb9d326653b6b5224f900c8c2e01af5c98ad) 后正常 运行环境 Chrome `127.0.6533.73` + Tampermonkey `5.1.1`，直播间为 https://live.bilibili.com/732

上一个版本能用的话，可能是房间类型判断出了问题，主要是之前B站改版，活动页面和普通页面使用了同样的URL，无法在房间加载之前判断是否执行屏蔽
