### ISSUE TITLE
请问bilibili直播净化的菜单怎么呼出来

### ISSUE THREAD

**Issue by 0772boy** [lzghzr/TampermonkeyJS#9]
看了介绍图片但是没找到在哪可以弹出设置- -||
恕我眼拙

**Comment by lzghzr** [comment]
可能是没加载出来？正常来说在弹幕输入上方有一个 "滚" 字
________________________________

**Comment by 0772boy** [comment]
木有啊。。。我Chrome65，版本没影响吧？
那我自己编辑代码吧里面的false都改成true也没效果啊。。。
     name: '看&nbsp;&nbsp;板&nbsp;&nbsp;娘',
            enable: true
        },
        noGuardIcon: {
            name: '舰队标识',
            enable: true
        },
        noHDIcon: {
            name: '活动标识',
            enable: true

**Comment by 0772boy** [comment]
另外两个插件是正常的。。。一个是B站直播全屏发弹幕的，一个是强制所有网页使用微软雅黑字体的- -||

**Comment by lzghzr** [comment]
那你可以试试把全屏发弹幕的关掉

**Comment by 0772boy** [comment]
关掉了直播全屏发弹幕，刷新了一次页面
再开启直播净化，刷新了一次页面
还是木有效果。。。算了，谢谢 T_T
